import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./header";
import Footer from "./footer";

export const metadata: Metadata = {
  title: "Week-1 Projects",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full">
        <div className="min-h-screen flex flex-col">
          <Header />
          <main className="w-full flex-1 flex justify-center items-center">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
